apiVersion: v2
name: k3s-monitoring
description: A Helm chart for monitoring a K3s cluster using Prometheus and Grafana
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
