prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    service:
      type: ClusterIP
    resources:
      limits:
        memory: 200Mi
      requests:
        memory: 100Mi
    persistentVolume:
      enabled: false
    extraScrapeConfigs:
      - job_name: 'kubernetes-nodes'
        static_configs:
          - targets: ['localhost:9100']

grafana:
  adminPassword: "admin"
  service:
    type: ClusterIP
  persistence:
    enabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://monitoring-prometheus-server.monitoring.svc.cluster.local
          isDefault: true

  sidecar:
    dashboards:
      enabled: true

  dashboards:
    default:
      k3s-monitoring:
        json: |
          {
            "annotations": {
              "list": [
                {
                  "builtIn": 1,
                  "datasource": "-- Grafana --",
                  "enable": true,
                  "hide": true,
                  "iconColor": "rgba(0, 211, 255, 1)",
                  "name": "Annotations & Alerts",
                  "target": {
                    "limit": 100,
                    "matchAny": false,
                    "tags": [],
                    "type": "dashboard"
                  },
                  "type": "dashboard"
                }
              ]
            },
            "description": "Monitors K3s cluster using Kube-Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.\n\nOrigin from  dashboard: 8721(K8s RKE cluster monitoring) and will be compatible with k3s",
            "editable": true,
            "gnetId": 15282,
            "graphTooltip": 1,
            "iteration": 1637425474742,
            "panels": [
              {
                "collapsed": false,
                "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
                "id": 34,
                "panels": [],
                "title": "Total usage",
                "type": "row"
              }
              // ... (REDACTED FOR LENGTH)
            ],
            "refresh": "1m",
            "schemaVersion": 32,
            "style": "dark",
            "tags": ["kubernetes", "prometheus"],
            "templating": {
              "list": [
                {
                  "allValue": ".*",
                  "current": {},
                  "datasource": "${DS_PROMETHEUS}",
                  "definition": "label_values(node)",
                  "includeAll": true,
                  "multi": false,
                  "name": "Node",
                  "query": {
                    "query": "label_values(node)",
                    "refId": "Prometheus-Node-Variable-Query"
                  },
                  "refresh": 1,
                  "type": "query"
                },
                {
                  "allValue": ".*",
                  "current": {},
                  "datasource": "${DS_PROMETHEUS}",
                  "includeAll": true,
                  "multi": true,
                  "name": "Namespace",
                  "query": {
                    "query": "label_values(namespace)",
                    "refId": "Prometheus-Namespace-Variable-Query"
                  },
                  "refresh": 1,
                  "type": "query"
                }
              ]
            },
            "time": {
              "from": "now-3h",
              "to": "now"
            },
            "timepicker": {
              "refresh_intervals": [
                "5s", "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d"
              ],
              "time_options": [
                "5m", "15m", "1h", "6h", "12h", "24h", "2d", "7d", "30d"
              ]
            },
            "timezone": "browser",
            "title": "K3S cluster monitoring",
            "uid": "1bI4P-xiz",
            "version": 9
          }
