prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    service:
      type: ClusterIP
    resources:
      limits:
        memory: 200Mi
      requests:
        memory: 100Mi
    persistentVolume:
      enabled: false
    extraScrapeConfigs:
      - job_name: 'kubernetes-nodes'
        static_configs:
          - targets: ['localhost:9100']

grafana:
  adminPassword: "admin"
  service:
    type: ClusterIP
  persistence:
    enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://monitoring-prometheus-server.monitoring.svc.cluster.local
          isDefault: true
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  dashboards:
    default:
      k3s-monitoring:
        gnetId: 15282
        revision: 1
        datasource: Prometheus
