apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: armory
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: armory
  project: default
  source:
    repoURL: https://github.com/alex-rosta/armory-helm.git
    targetRevision: HEAD
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true